import React from "react";
import Head from "next/head";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { InternetCheck } from "@/utils";
import { Footer } from "@/components/Footer/footer";
import { Navbar } from "@/components/Navbar/navbar";
import { ThemeProvider } from "@/utils/theme-provider";

const inter = Inter({ subsets: ["latin"] });
// const poppins = Poppin({
//   weight: ["300", "400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Coast Research Technology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script src="/flickity.pkgd.min.js" async></script>
      </Head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <InternetCheck />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
