import React from 'react';
import AboutSection from '@/views/aboutSection';
import ServicesSection from '@/views/servicesSection';
import BlobApp from '@/views/bubblesBackground';
import Carousel from '@/components/AllCarousel/HeroCarousel/carousel';
import { slides, testimonial } from '@/lib/data';
import TestimonialCarousel from '@/components/AllCarousel/TestimonialCarousel/TestimialCarousel';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home | Coast Research Technology',
  description: 'Generated by create next app',
};

const Home: React.FC = () => {
  // const OPTIONS: EmblaOptionsType = { loop: true };
  // const SLIDE_COUNT = 8;
  // const SLIDES = Array.from(Array(SLIDE_COUNT).keys());

  return (
    <main>
      <section className="primarySection">
        <h1>COAST RESEARCH TECHNOLOGY</h1>
        <p>
          At Coast Research Technology, our mission is simple: &quot;Making life
          easier through smart coding.&quot; We believe in the power of
          technology to transform lives, and we work tirelessly to ensure that
          our clients and trainees are always a step ahead.
        </p>
      </section>
      {/* Hero Section Slider */}
      <Carousel slides={slides} />

      {/* About Us Section */}
      <AboutSection />

      {/* Services Section */}
      <ServicesSection />

      <BlobApp />

      <TestimonialCarousel slides={testimonial} />
    </main>
  );
};

export default Home;
